require("user.lazy")
require("user.options")
require("user.keymaps")
require("user.plugins.color")
require("user.plugins.telescope")
require("user.plugins.tree-sitter")
require("user.plugins.lualine")
